### ISSUE TITLE
http_host_aliases Not Respected

### ISSUE THREAD

**Issue by matdave** [chsmedien/XRouting#14]
I have "http_host_aliases" set in all of my contexts, but it doesn't seem to be _firing_.

**Comment by christianseel** [comment]
Hi Mat,
but the routing based on your http_host works? Did you add your hosts *without* the `www.` subdomain? (www is added automatically by XRouting).

**Comment by christianseel** [comment]
You might want to try the debug mode in the latest 1.4.1 release (released today) and paste the output here. Then it should be easy to find the issue.

**Comment by matdave** [comment]
I will try that after peak hours today.  I have a completely different domain name that wasn't working, but that brings up a question...  How would you set it up if you want www.example.com to be the primary domain name.  For that, we have just been using .htaccess, but I was wondering if setting the http_host to www.example.com and the http_host_aliases to example.com would work.

**Comment by christianseel** [comment]
XRouting won't redirect the visitors. XRouting will just show the matched context. You still need something else for the redirect (htaccess works best).

If you want to use `www.example.com` as `http_host` you need to disable the `xrouting.include_www` setting.
