### ISSUE TITLE
Wrong image paths created by pthumb 

### ISSUE THREAD

**Issue by sonicpunk** [chsmedien/XRouting#15]
Hi Chris,

In my current project I am trying out Xrouting for a multilanguage site.  When I use pthumb to create images, it is adding the base_url '/de/' to the path name of the image.  But actually the 'de' folder does not exist on the server.
How do you take care of this problem?

Cheers,
Ben

**Comment by sonicpunk** [comment]
I seem to have found a solution:  in the phpthumbof settings by pThumb Cache I found the setting "Override Cache URL".  Here you can place your domain and it creates absolute links to the cache folder, going around the context settings.

**Comment by christianseel** [comment]
Yeah you need to make sure that it's generating absolute URLs. You might want to use a 2nd mediasource with a absolute base_url (relative setting disabled) or change the override setting of pthumb.

**Comment by sonicpunk** [comment]
I am having this problem again.  I am using a second media source for my contentblocks and redactor image inputs, but it keeps writing the base url from the context settings into my image url in the manager.

![screen shot 2015-12-29 at 15 35 43](https://cloud.githubusercontent.com/assets/447453/12035981/125ec1a0-ae42-11e5-8f53-c8c2af4201ef.png)

**Comment by sonicpunk** [comment]
If I start the path with a (/) in the baseUrl than it appears to work

![screen shot 2015-12-29 at 16 12 05](https://cloud.githubusercontent.com/assets/447453/12036517/fc9c4af4-ae46-11e5-9845-92c16766d829.png)

**Comment by sonicpunk** [comment]
For Redactor it is also important to have the plugin_baseurls to be set to NO

Way too many settings need to be looked at for this!

![screen shot 2015-12-29 at 16 21 50](https://cloud.githubusercontent.com/assets/447453/12036657/57c5bf18-ae48-11e5-9402-526ef34597e4.png)
