### ISSUE TITLE
MODX Cloud dev accounts?

### ISSUE THREAD

**Issue by sottwell** [chsmedien/XRouting#16]
Can this be used on MODX Cloud accounts where the subdomain URL would be something like "sub.blah.sottwell.modxcloud.com"? I've tried it and am just getting the 'not found' page, but I'm not sure what the settings should be in this case, or if it will even work.

**Comment by christianseel** [comment]
Hi Susan! Yes this should absolutely work! Just the same way as for other setups! It you need help ping me on slack or feel free to post your XRouting debug info here (info on how to generate the debut output is in the readme.

**Comment by sottwell** [comment]
hugopeek helped me with the correct settings on Slack, and it is working perfectly.
