### ISSUE TITLE
note contexts found

### ISSUE THREAD

**Issue by brescianicri** [chsmedien/XRouting#18]
In my installation XRouting doesn't found the contexts.
this instaction:
 $modx_base_url = $modx->getOption('base_url', null, MODX_BASE_URL);
$requestUrl = str_replace('//','/',$modx_base_url.$_REQUEST[$modx->getOption('request_param_alias', null, 'q')]);

$requestUrl is '/'

foreach ((array) $matched_contexts as $index => $ckey) {
                
                $context = $contexts[$ckey];
                $strpos = strpos($requestUrl, $contexts[$ckey]['base_url']);

                if ($strpos === 0) {
                    $matches[strlen($contexts[$ckey]['base_url'])] = $ckey;
                }
}

In this cycle don't maches beacause $contexts[$ckey]['base_url'] is '/en/'

But i have configure the context in the right way.

**Comment by brescianicri** [comment]
In my opinion the problem is this:
$modx_base_url = $modx->getOption('base_url', null, MODX_BASE_URL);

the $modx_base_url is not the right base_url but "/", you have the solution ?

**Comment by christianseel** [comment]
Hey, could you please post your XRouting Debug info together with the URL you're trying to request? Thanks!

I'm not sure, but it could be a not yet handled edge case…

**Comment by brescianicri** [comment]
XRouting doesn't write log i see this on modx log:
include.cache.php : 162) PHP notice: Undefined index: xrouting-debug

Maybe i found a solution, i modify the code:

  // find matching hosts
            $matched_contexts = $contexts['_hosts'][$http_host];

            //Cristian Bizen 20 10 2016 i overwrite the base url with the current
            foreach ((array) $matched_contexts as $index => $ckey) {
                
                $context = $contexts[$ckey];
                $strpos = strpos($requestUrl, $contexts[$ckey]['base_url']);

                if ($contexts[$ckey]['cultureKey'] == $_REQUEST['cultureKey']) {
                    $modx_base_url = $contexts[$ckey]['base_url'];
					$requestUrl = str_replace('//','/',$modx_base_url.$_REQUEST[$modx->getOption('request_param_alias', null, 'q')]);
                }
            }


			foreach ((array) $matched_contexts as $index => $ckey) {
                
                $context = $contexts[$ckey];
                $strpos = strpos($requestUrl, $contexts[$ckey]['base_url']);

                if ($strpos === 0) {
                    $matches[strlen($contexts[$ckey]['base_url'])] = $ckey;
                }
            }

**Comment by christianseel** [comment]
Do you have any redirect/language specific stuff in your htaccess? I'm wondering because there should be no `$_REQUEST['cultureKey']` set from anywhere…

XRouting requires no changes to your default MODX htaccess file…

**Comment by christianseel** [comment]
You can find infos about how to enable the XRouting debug output here: https://github.com/chsmedien/XRouting#troubleshooting

**Comment by brescianicri** [comment]
Ok the problem is the htaccess.

**Comment by christianseel** [comment]
Perfect :)
