### ISSUE TITLE
Symlinks Across Different Contexts Result in 503

### ISSUE THREAD

**Issue by digitalpenguin** [chsmedien/XRouting#23]
Fantastic Extra. 

Only issue I'm having is if I create a symlink on a second context that points to a resource on the first context, viewing the symlink gives a 503 error.

Symlinks within the same contexts still work fine.

**Comment by christianseel** [comment]
Hi @digitalpenguin,

did you check your `allow_forward_across_contexts` system setting? This needs to be enabled to allow MODX to do cross-context symlinks!

**Comment by digitalpenguin** [comment]
Aha! Thank you Christian! :)
