### ISSUE TITLE
Problem with modx 2.5 and/or babel 3.0.0rc1

### ISSUE THREAD

**Issue by funkyduke** [chsmedien/XRouting#24]
Since the upgrade to Modx 2.5 (from 2.4.3) and babel 3.0.0rc1 (from beta4) XRouting is not working anymore. Before the upgrade everything went great. Any known issues?

**Comment by funkyduke** [comment]
Strange, when changing a system setting of Xrouting (and then changing it back) everything works again. Very strange. (I had cleared the cache before and this wasn't helping)

**Comment by christianseel** [comment]
That sounds like a caching issue… I didn't test XRouting with 2.5 yet, but there should be no breaking changes so it's expected to keep working…

According to your 2nd comment it's also working fine for you know?

**Comment by funkyduke** [comment]
For the moment yes. I keep you updated if something goes wrong.

**Comment by funkyduke** [comment]
Hey Christianseel, I'm sorry to inform you that the problem is back. After disabling the gateway plugin of babel and then reactivating it everything works again normal. Very strange. There must be somewhere a problem between xrouting en babel I think. Everything is on the latest version (xrouting, babel, modx). the debug info shows no errors in my opinion.

**Comment by funkyduke** [comment]
So, I have been able to locate the problem a little bit closer: when I disable the plugin gateway (used with babel) then xrouting is doing his job, but off-course babel isn't working good at that point. Enabling the plugin gateway results in xrouting not working anymore. For the record: I have 3 contexts: web, fr and se. The culturekeys are nl (web), fr (fr), rs (se). The fr is working with babel (www.website.com/fr), the rs is working with xrouting (www.website.rs). So with the gateway plugin enabled surfing at www.website.rs results in www.website.com.

**Comment by funkyduke** [comment]
I have fixed it for the moment in the gateway with:
`if(($modx->context->get('key') != "mgr") && ($modx->context->get('key') != "se"))`

**Comment by christianseel** [comment]
What are you using the gateway plugin for? Normally xrouting should completely replace that! It's not intended to use both because they are doing the same job (while xrouting is more flexible from my point of view)

**Comment by christianseel** [comment]
You migh wanna read through this short tutorial: https://modx.today/posts/2015/05/using-xrouting-for-multilingual-websites-in-modx

**Comment by funkyduke** [comment]
If I don't use the gateway then Babel isn't working. The FR goes to www.website.com/fr/ and the SE goes to www.website.rs. So the base-url on SE is just /. (also on www.website.com)

**Comment by goldsky** [comment]
How about this? https://gist.github.com/goldsky/e926167132e227e2f10f
